Configure containers to exit on error during a migration. Fixes #32

diff --git a/php/7.4/fpm/etc/cont-init.d/50-laravel-automations b/php/7.4/fpm/etc/cont-init.d/50-laravel-automations
--- a/php/7.4/fpm/etc/cont-init.d/50-laravel-automations
+++ b/php/7.4/fpm/etc/cont-init.d/50-laravel-automations
@@ -1,5 +1,8 @@
 #!/usr/bin/with-contenv bash
 
+# Exit on error
+set -e
+
 # Check to see if an Artisan file exists and assume means Laravel is configured.
 if [ -f $WEBUSER_HOME/artisan ]; then
     ############################################################################
