Added NGINX healthcheck support

diff --git a/src/variations/fpm-nginx/etc/s6-overlay/s6-rc.d/nginx/data/check b/src/variations/fpm-nginx/etc/s6-overlay/s6-rc.d/nginx/data/check
--- a/src/variations/fpm-nginx/etc/s6-overlay/s6-rc.d/nginx/data/check
+++ b/src/variations/fpm-nginx/etc/s6-overlay/s6-rc.d/nginx/data/check
@@ -1,20 +1,11 @@
 #!/command/with-contenv sh
-if [ "$SSL_MODE" = "off" ]; then
-	curl_options="--location --silent --show-error"
-	http_port=8080
-	http_scheme=http
-else
-	curl_options="--location --insecure --silent --show-error"
-	http_port=8443
-	http_scheme=https
-fi
+response=$(curl --fail --location --insecure --silent --show-error http://localhost:8080/ping)
 
-response=$(curl $curl_options $http_scheme://localhost:$http_port/ping)
-
+# Check the response
 if [ "$response" = "pong" ]; then
-	echo "✅ NGINX + PHP-FPM is running correctly."
-	exit 0
+    echo "✅ NGINX + PHP-FPM is running correctly."
+    exit 0
 else
-	echo "❌ There seems to be a failure in checking the NGINX + PHP-FPM. Trying again..."
-	exit 1
+    echo "❌ There seems to be a failure in checking the NGINX + PHP-FPM. Trying again..."
+    exit 1
 fi
